name: newsletter-api

services:
  traefik:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik-dev.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic-dev.yml:/etc/traefik/dynamic.yml
    networks:
      - newsletter-api-net

  db:
    image: postgres:17.4
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - newsletter-api-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  newsletter-service:
    build:
      context: .
      dockerfile: services/newsletter-service/Dockerfile
      target: dev
    container_name: newsletter-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./services/newsletter-service:/app/services/newsletter-service
      - ./pkg:/app/pkg
    networks:
      - newsletter-api-net
    command: ["air", "-c", "services/newsletter-service/.air.toml"]
    depends_on:
      - db
      - traefik

  subscription-service:
    build:
      context: .
      dockerfile: services/subscription-service/Dockerfile
      target: dev
    container_name: subscription-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    volumes:
      - ./services/subscription-service:/app/services/subscription-service
      - ./pkg:/app/pkg
    networks:
      - newsletter-api-net
    command: ["air", "-c", "services/subscription-service/.air.toml"]
    depends_on:
      - db
      - traefik

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
      target: dev
    container_name: user-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - ./services/user-service:/app/services/user-service
      - ./pkg:/app/pkg
    networks:
      - newsletter-api-net
    command: ["air", "-c", "services/user-service/.air.toml"]
    depends_on:
      - db
      - traefik

networks:
  newsletter-api-net:
    driver: bridge
