name: newsletter-api

services:
  traefik:
    image: traefik:v3.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
    networks:
      - newsletter-api-net

  db:
    image: postgres:17.4
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - newsletter-api-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  newsletter-service:
    build:
      context: .
      dockerfile: services/newsletter-service/Dockerfile
      target: prod
    container_name: newsletter-service
    ports:
      - "8081:8081"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - newsletter-api-net
    depends_on:
      - db
      - traefik

  subscription-service:
    build:
      context: .
      dockerfile: services/subscription-service/Dockerfile
      target: prod
    container_name: subscription-service
    ports:
      - "8082:8082"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
        - ./services/subscription-service:/app/services/subscription-service
        - ./pkg:/app/pkg
        - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
    networks:
      - newsletter-api-net
    depends_on:
      - db
      - traefik

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
      target: dev
    container_name: user-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./services/user-service:/app/services/user-service
      - ./pkg:/app/pkg
      - ./secrets/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json:ro
    networks:
      - newsletter-api-net
    command: [ "air", "-c", "services/user-service/.air.toml" ]
    depends_on:
      - db
      - traefik

networks:
  newsletter-api-net:
    driver: bridge

volumes:
  db_data:
    driver: local