name: newsletter-api

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true" # for dev only (TODO: secure auth for prod)
      - "--api.dashboard=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
    networks:
      - newsletter-api-net

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    networks:
      - newsletter-api-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  newsletter-service:
    build:
      context: .
      dockerfile: services/newsletter-service/Dockerfile
      target: prod
    container_name: newsletter-service
    env_file:
      - .env
    networks:
      - newsletter-api-net
    depends_on:
      - db
      - traefik

  subscription-service:
    build:
      context: .
      dockerfile: services/subscription-service/Dockerfile
      target: prod
    container_name: subscription-service
    env_file:
      - .env
    networks:
      - newsletter-api-net
    depends_on:
      - db
      - traefik

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
      target: prod
    container_name: user-service
    env_file:
      - .env
    networks:
      - newsletter-api-net
    depends_on:
      - db
      - traefik

networks:
  newsletter-api-net:
    driver: bridge
