entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
  insecure: true
  dashboard: true

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG

certificatesResolvers:
  letsencrypt:
    acme:
      email: kovm24@vse.cz
      storage: acme.json
      httpChallenge:
        entryPoint: web