openapi: 3.0.3
info:
  title: User Service
  description: User service allowing to manage users (editors of newsletters).
  version: 1.0.0
servers:
  - url: http://localhost:80/v1
    description: API Gateway route

paths:
  "/ping":
    get:
      description: Health check
      operationId: Ping
      summary: Check the healthiness of the service
      responses:
        "204":
          description: It's ALIVE (a.k.a. service is up and running)
        "400":
          description: Invalid request
  "/users": {
    # TODO;

    # /users/{:id}
    # ...
  }
components: {}
